name = "augtoken-manager"
main = "src/index.ts"
compatibility_date = "2025-09-20"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
ALLOWED_ORIGINS = "https://your-domain.com,https://token-manager.your-domain.com"
SESSION_EXPIRES_IN = "24h"
RATE_LIMIT_LOGIN = "10"
RATE_LIMIT_API = "100"

[[kv_namespaces]]
binding = "USERS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

[[kv_namespaces]]
binding = "TOKENS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

# Production secrets (use: wrangler secret put SECRET_NAME)
# JWT_SECRET - Secret key for JWT signing
# ADMIN_PASSWORD - Admin login password
# EMAIL_API_KEY - Email service API key (optional)