name = "augtoken-manager-dev"
main = "src/index.ts"
compatibility_date = "2025-09-20"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
SESSION_EXPIRES_IN = "24h"
RATE_LIMIT_LOGIN = "50"
RATE_LIMIT_API = "500"

[[kv_namespaces]]
binding = "USERS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

[[kv_namespaces]]
binding = "TOKENS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "1c0df174578c426e96d70e94eeca03bc"

# Development secrets (use: wrangler secret put SECRET_NAME --env dev)
# JWT_SECRET - Secret key for JWT signing
# ADMIN_PASSWORD - Admin login password
# EMAIL_API_KEY - Email service API key (optional)
